version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo:4.2.0
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 27017:27017

  backend:
    container_name: backend
    build: "."
    ports:
      - 443:3000
    environment:
      - PORT=3000
      - GRAPHQL_ROUTE=/graphql
      - MONGODB_URI=mongodb://mongo/cookieman
      - NODE_ENV=PRODUCTION
    depends_on:
      - mongo
